/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.City;
import Model.Community;
import Model.Encounter;
import Model.EncounterHistory;
import Model.House;
import Model.Patient;
import Model.PatientDirectory;
import Model.Person;
import Model.PersonDirectory;
import Model.VitalSigns;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.time.ZoneId;
import java.util.Locale;
import javax.swing.JFileChooser;
import java.util.*; 

/**
 *
 * @author siddharthasavant
 */
public class EncounterPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private JPanel rightPane;
    private Person person;
    private Patient patient;
    private PatientDirectory patientDirectory;
    private Encounter encounter;
    private EncounterHistory encounterHistory;
    private VitalSigns vitalSigns;
    
        
    public EncounterPanel(JPanel rightPane, Person person, EncounterHistory encounterHistory, PatientDirectory patientDirectory) {
        initComponents();
        this.rightPane = rightPane;
        this.person = person;
        this.patientDirectory = patientDirectory;
        this.encounterHistory = encounterHistory;
        populateDetails();
    }
    
     private void populateDetails(){
        txtPatientId.setText(person.getId());
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtGender.setText(person.getGender());
        txtAge.setText(Integer.toString(person.getAge()));
        txtAddressLine1.setText(person.getHouse().getAddress());
        txtAddressLine2.setText(person.getHouse().getCommunity().getCommunityName());
        txtCityName.setText(person.getHouse().getCommunity().getCity().getCityName());
        
        txtPatientId.setEnabled(false);
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtGender.setEnabled(false);
        txtAge.setEnabled(false);
        txtAddressLine1.setEnabled(false);
        txtAddressLine2.setEnabled(false);
        txtCityName.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMC = new javax.swing.ButtonGroup();
        buttonGroupA = new javax.swing.ButtonGroup();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAddressLine1 = new javax.swing.JLabel();
        txtAddressLine1 = new javax.swing.JTextField();
        lblAddressLine2 = new javax.swing.JLabel();
        txtAddressLine2 = new javax.swing.JTextField();
        btnPatientData = new javax.swing.JButton();
        txtCityName = new javax.swing.JTextField();
        lblCityName = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        lblBodyTemperature = new javax.swing.JLabel();
        txtBodyTemperature = new javax.swing.JTextField();
        lblPulseRate = new javax.swing.JLabel();
        txtPulseRate = new javax.swing.JTextField();
        lblRespiratoryRate = new javax.swing.JLabel();
        txtRespiratoryRate = new javax.swing.JTextField();
        lblSystolicBP = new javax.swing.JLabel();
        txtSystolicBP = new javax.swing.JTextField();
        lblDiastolicBP = new javax.swing.JLabel();
        txtDiastolicBP = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSearchAbnormal = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(128, 209, 223));

        lblFirstName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(10, 48, 58));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFirstName.setText("First Name:");

        txtFirstName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });

        lblLastName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(10, 48, 58));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLastName.setText("Last Name:");

        txtLastName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(10, 48, 58));
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender:");

        txtGender.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        txtGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGenderKeyReleased(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(10, 48, 58));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");

        txtAge.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        lblAddressLine1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAddressLine1.setForeground(new java.awt.Color(10, 48, 58));
        lblAddressLine1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddressLine1.setText("Address Line 1:");

        txtAddressLine1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine1ActionPerformed(evt);
            }
        });
        txtAddressLine1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressLine1KeyReleased(evt);
            }
        });

        lblAddressLine2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAddressLine2.setForeground(new java.awt.Color(10, 48, 58));
        lblAddressLine2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddressLine2.setText("Address Line 2:");

        txtAddressLine2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine2ActionPerformed(evt);
            }
        });
        txtAddressLine2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressLine2KeyReleased(evt);
            }
        });

        btnPatientData.setBackground(new java.awt.Color(255, 255, 255));
        btnPatientData.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        btnPatientData.setForeground(new java.awt.Color(251, 131, 106));
        btnPatientData.setText("Submit Patient Data");
        btnPatientData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientDataActionPerformed(evt);
            }
        });

        txtCityName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityNameActionPerformed(evt);
            }
        });
        txtCityName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityNameKeyReleased(evt);
            }
        });

        lblCityName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCityName.setForeground(new java.awt.Color(10, 48, 58));
        lblCityName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCityName.setText("City Name:");

        lblPatientId.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPatientId.setForeground(new java.awt.Color(10, 48, 58));
        lblPatientId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientId.setText("Patient ID:");

        txtPatientId.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIdActionPerformed(evt);
            }
        });
        txtPatientId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatientIdKeyReleased(evt);
            }
        });

        lblBodyTemperature.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblBodyTemperature.setForeground(new java.awt.Color(10, 48, 58));
        lblBodyTemperature.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBodyTemperature.setText("Body Temperature:");

        txtBodyTemperature.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtBodyTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodyTemperatureActionPerformed(evt);
            }
        });
        txtBodyTemperature.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBodyTemperatureKeyReleased(evt);
            }
        });

        lblPulseRate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPulseRate.setForeground(new java.awt.Color(10, 48, 58));
        lblPulseRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPulseRate.setText("Pulse Rate:");

        txtPulseRate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtPulseRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulseRateActionPerformed(evt);
            }
        });
        txtPulseRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPulseRateKeyReleased(evt);
            }
        });

        lblRespiratoryRate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblRespiratoryRate.setForeground(new java.awt.Color(10, 48, 58));
        lblRespiratoryRate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRespiratoryRate.setText("Respiratory  Rate:");

        txtRespiratoryRate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRespiratoryRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespiratoryRateActionPerformed(evt);
            }
        });
        txtRespiratoryRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRespiratoryRateKeyReleased(evt);
            }
        });

        lblSystolicBP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSystolicBP.setForeground(new java.awt.Color(10, 48, 58));
        lblSystolicBP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSystolicBP.setText("Systolic Blood Pressure:");

        txtSystolicBP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtSystolicBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSystolicBPActionPerformed(evt);
            }
        });
        txtSystolicBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSystolicBPKeyReleased(evt);
            }
        });

        lblDiastolicBP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblDiastolicBP.setForeground(new java.awt.Color(10, 48, 58));
        lblDiastolicBP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiastolicBP.setText("Diastolic Blood Pressure:");

        txtDiastolicBP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtDiastolicBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiastolicBPActionPerformed(evt);
            }
        });
        txtDiastolicBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiastolicBPKeyReleased(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(32, 37, 113));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSearchAbnormal.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchAbnormal.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        btnSearchAbnormal.setForeground(new java.awt.Color(251, 131, 106));
        btnSearchAbnormal.setText("Search Cases");
        btnSearchAbnormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAbnormalActionPerformed(evt);
            }
        });

        lblTitle1.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle1.setFont(new java.awt.Font("Luminari", 1, 35)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(10, 48, 58));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Beth Israel Deaconess Medical Center");
        lblTitle1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblTitle2.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle2.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(10, 48, 58));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Address: 330 Brookline Ave, Boston, MA 02215  Phone: (617) 667-7000");

        lblTitle3.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle3.setFont(new java.awt.Font("Lucida Grande", 3, 30)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(10, 48, 58));
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Encounter Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBodyTemperature)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAddressLine1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                                        .addComponent(lblAddressLine2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCityName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPatientId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAddressLine2)
                                        .addComponent(txtAddressLine1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCityName)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtPatientId, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                                .addComponent(txtGender)
                                                .addComponent(txtLastName))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPulseRate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblRespiratoryRate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(btnPatientData, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)
                                .addComponent(btnSearchAbnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lblSystolicBP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSystolicBP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(lblDiastolicBP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiastolicBP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle2)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(11, 11, 11)
                .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSystolicBP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSystolicBP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiastolicBP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiastolicBP, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPatientData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAbnormal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAddressLine1, lblAddressLine2, lblAge, lblCityName, lblFirstName, lblGender, lblLastName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAddressLine1, txtAddressLine2, txtAge, txtCityName, txtFirstName, txtGender, txtLastName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPatientData, btnSearchAbnormal});

    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine1ActionPerformed

    private void txtAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine2ActionPerformed

    private void btnPatientDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientDataActionPerformed
        // TODO add your handling code here:
        String patientId = person.getId();
        int bodyTemperature;
        try{
            bodyTemperature = Integer.parseInt(txtBodyTemperature.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: Enter Correct Body Temperature");
            return;
        }
        
        int pulseRate;
        try{
            pulseRate = Integer.parseInt(txtPulseRate.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: Enter Correct Pulse Rate");
            return;
        }
        
        int respiratoryRate;
        try{
            respiratoryRate = Integer.parseInt(txtRespiratoryRate.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: Enter Correct Respiratory Rate");
            return;
        }
        
        float systolicBP;
        try{
            systolicBP = Float.parseFloat(txtSystolicBP.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: Enter Correct Systolic Blood Pressure");
            return;
        }
        
        float diastolicBP;
        try{
            diastolicBP = Float.parseFloat(txtDiastolicBP.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: Enter Correct Diastolic Blood Pressure");
            return;
        }
        
        float[] bloodPressure = new float[]{systolicBP, diastolicBP};
        
        if(patientDirectory.getPatientDirectory().isEmpty()){
            patient = new Patient(person, person.getId());
            System.out.println("New Patient is created for the first time");
        }
        
        for(Patient p: patientDirectory.getPatientDirectory()){
            if(!p.getId().equals(patientId)){
                patient = new Patient(person, person.getId());
                System.out.println("New Patient is created");
            }else{
                patient = p; 
                System.out.println("Old patient");
            }
        }
        
        if(!patientDirectory.patientExists(patient)){
            patientDirectory.addPatient(patient);
        }
        
        encounter = new Encounter();
        vitalSigns = new VitalSigns();
        vitalSigns.setBodyTemperature(bodyTemperature);
        vitalSigns.setPulseRate(pulseRate);
        vitalSigns.setRespiratoryRate(respiratoryRate);
        vitalSigns.setBloodPressure(bloodPressure);
        encounter.setPatient(patient);
        encounter.setVitalSigns(vitalSigns);
        
        
        
        encounterHistory.addEncounter(encounter);
        
        
        
        if(txtBodyTemperature.getText().isEmpty() || txtPulseRate.getText().isEmpty() || txtRespiratoryRate.getText().isEmpty()
                || txtSystolicBP.getText().isEmpty() || txtDiastolicBP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Entered Empty Data. Please try again");
            return;
        }
        
        
        JOptionPane.showMessageDialog(null, "Encounter Details Sucessfully Added");
        System.out.println(encounter.getPatient().getHouse().getCommunity().getHouseSet());
        System.out.println(encounter.getPatient().getHouse().getCommunity().getCity().getCommunitySet());
    }//GEN-LAST:event_btnPatientDataActionPerformed

    private void txtCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityNameActionPerformed

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        // TODO add your handling code here:
//        Pattern pattern = Pattern.compile("^[a-zA-z]{0,30}$");
//        Matcher match = pattern.matcher(txtFirstName.getText());
//        boolean matchFound = match.matches();
//        if(!matchFound){
//            jLabel2.setText("Enter valid input data");
//        }else{
//            jLabel2.setText(null);
//        }
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        // TODO add your handling code here:
//        Pattern pattern = Pattern.compile("^[a-zA-z0-9]{0,30}$");
//        Matcher match = pattern.matcher(txtLastName.getText());
//        boolean matchFound = match.find();
//        if(!matchFound){
//            jLabel3.setText("Enter valid input data");
//        }else{
//            jLabel3.setText(null);
//        }
    }//GEN-LAST:event_txtLastNameKeyReleased

    private void txtGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenderKeyReleased
        // TODO add your handling code here:
//        Pattern pattern = Pattern.compile("^[a-zA-z0-9]{0,30}$");
//        Matcher match = pattern.matcher(txtGender.getText());
//        boolean matchFound = match.find();
//        if(!matchFound){
//            jLabel4.setText("Enter valid input data");
//        }else{
//            jLabel4.setText(null);
//        }
    }//GEN-LAST:event_txtGenderKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
//        Pattern pattern = Pattern.compile("^[1-9]{1,2}$");
//        Matcher match = pattern.matcher(txtAge.getText());
//        boolean matchFound = match.find();
//        if(!matchFound){
//            jLabel5.setText("Enter valid input data");
//        }else{
//            jLabel5.setText(null);
//        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtAddressLine1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressLine1KeyReleased
        // TODO add your handling code here:
//        Pattern pattern = Pattern.compile("^[a-zA-z0-9]{0,30}$");
//        Matcher match = pattern.matcher(txtAddressLine1.getText());
//        boolean matchFound = match.find();
//        if(!matchFound){
//            jLabel6.setText("Enter valid input data");
//        }else{
//            jLabel6.setText(null);
//        }
    }//GEN-LAST:event_txtAddressLine1KeyReleased

    private void txtAddressLine2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressLine2KeyReleased
        // TODO add your handling code here:
//        Pattern pattern = Pattern.compile("^[a-zA-z]{0,30}$");
//        Matcher match = pattern.matcher(txtAddressLine2.getText());
//        boolean matchFound = match.find();
//        if(!matchFound){
//            jLabel7.setText("Enter valid input data");
//        }else{
//            jLabel7.setText(null);
//        }
    }//GEN-LAST:event_txtAddressLine2KeyReleased

    private void txtCityNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityNameKeyReleased
        // TODO add your handling code here:
//        Pattern pattern = Pattern.compile("^[a-zA-z]{0,30}$");
//        Matcher match = pattern.matcher(txtCityName.getText());
//        boolean matchFound = match.find();
//        if(!matchFound){
//            jLabel8.setText("Enter valid input data");
//        }else{
//            jLabel8.setText(null);
//        }
    }//GEN-LAST:event_txtCityNameKeyReleased

    private void txtPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIdActionPerformed

    private void txtPatientIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIdKeyReleased

    private void txtBodyTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodyTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodyTemperatureActionPerformed

    private void txtBodyTemperatureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBodyTemperatureKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodyTemperatureKeyReleased

    private void txtPulseRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulseRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulseRateActionPerformed

    private void txtPulseRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPulseRateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulseRateKeyReleased

    private void txtRespiratoryRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespiratoryRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespiratoryRateActionPerformed

    private void txtRespiratoryRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespiratoryRateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespiratoryRateKeyReleased

    private void txtSystolicBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSystolicBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSystolicBPActionPerformed

    private void txtSystolicBPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSystolicBPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSystolicBPKeyReleased

    private void txtDiastolicBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiastolicBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiastolicBPActionPerformed

    private void txtDiastolicBPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiastolicBPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiastolicBPKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPane.remove(this);
        CardLayout layout = (CardLayout) rightPane.getLayout();
        layout.previous(rightPane);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchAbnormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAbnormalActionPerformed
        // TODO add your handling code here:
        SearchJPanel searchJPanel = new SearchJPanel(rightPane, patientDirectory, encounterHistory);      
        rightPane.add("SearchJPanel", searchJPanel);
        CardLayout layout = (CardLayout) rightPane.getLayout();
        layout.next(rightPane);
    }//GEN-LAST:event_btnSearchAbnormalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPatientData;
    private javax.swing.JButton btnSearchAbnormal;
    private javax.swing.ButtonGroup buttonGroupA;
    private javax.swing.ButtonGroup buttonGroupMC;
    private javax.swing.JLabel lblAddressLine1;
    private javax.swing.JLabel lblAddressLine2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBodyTemperature;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblDiastolicBP;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPulseRate;
    private javax.swing.JLabel lblRespiratoryRate;
    private javax.swing.JLabel lblSystolicBP;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBodyTemperature;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtDiastolicBP;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPulseRate;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtSystolicBP;
    // End of variables declaration//GEN-END:variables
}
