/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.City;
import Model.Community;
import Model.House;
import Model.Person;
import Model.PersonDirectory;
import static UI.CreateJPanel.cityMap;
import static UI.CreateJPanel.communityMap;
import static UI.CreateJPanel.houseMap;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author siddharthasavant
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    private JPanel rightPane;
    private Person person;
    private DefaultTableModel dtm;
    private PersonDirectory personDirectory;
    private Person personOriginal;
    
    public UpdateJPanel(JPanel rightPane, Person person, DefaultTableModel dtm, PersonDirectory personDirectory) {
        initComponents();
        this.rightPane = rightPane;
        this.person = person;
        this.dtm = dtm;
        this.personDirectory = personDirectory;
        populateDetails();
        personOriginal = personDirectory.personFromOriginal(person);
    }
    
    private void populateDetails(){
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtGender.setText(person.getGender());
        txtAge.setText(Integer.toString(person.getAge()));
        txtAddressLine1.setText(person.getHouse().getAddress());
        txtAddressLine2.setText(person.getHouse().getCommunity().getCommunityName());
        txtCityName.setText(person.getHouse().getCommunity().getCity().getCityName());
        
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtGender.setEnabled(true);
        txtAge.setEnabled(true);
        txtAddressLine1.setEnabled(true);
        txtAddressLine2.setEnabled(true);
        txtCityName.setEnabled(true);
    }
    
    private void populateTable(){
        dtm.setRowCount(0); 
        for(Person person: personDirectory.getTemporaryPersonDirectory()){
            Object[] row = new Object[10];
            row[0] = person.getFirstName();
            row[1] = person.getLastName();
            row[2] = person.getGender();
            row[3] = person.getAge();
            row[4] = person.getHouse().getAddress();
            row[5] = person.getHouse().getCommunity().getCommunityName();
            row[6] = person.getHouse().getCommunity().getCity().getCityName();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAddressLine1 = new javax.swing.JLabel();
        txtAddressLine1 = new javax.swing.JTextField();
        lblAddressLine2 = new javax.swing.JLabel();
        txtAddressLine2 = new javax.swing.JTextField();
        btnPerson = new javax.swing.JButton();
        txtCityName = new javax.swing.JTextField();
        lblCityName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(200, 219, 245));

        lblFirstName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(10, 48, 58));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFirstName.setText("First Name:");

        txtFirstName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });

        lblLastName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(10, 48, 58));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLastName.setText("Last Name:");

        txtLastName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(10, 48, 58));
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender:");

        txtGender.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });
        txtGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGenderKeyReleased(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(10, 48, 58));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");

        txtAge.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        lblAddressLine1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAddressLine1.setForeground(new java.awt.Color(10, 48, 58));
        lblAddressLine1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddressLine1.setText("Address Line 1:");

        txtAddressLine1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine1ActionPerformed(evt);
            }
        });
        txtAddressLine1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressLine1KeyReleased(evt);
            }
        });

        lblAddressLine2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAddressLine2.setForeground(new java.awt.Color(10, 48, 58));
        lblAddressLine2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddressLine2.setText("Address Line 2:");

        txtAddressLine2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine2ActionPerformed(evt);
            }
        });
        txtAddressLine2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressLine2KeyReleased(evt);
            }
        });

        btnPerson.setBackground(new java.awt.Color(255, 255, 255));
        btnPerson.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        btnPerson.setForeground(new java.awt.Color(251, 131, 106));
        btnPerson.setText("Update Person");
        btnPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonActionPerformed(evt);
            }
        });

        txtCityName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtCityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityNameActionPerformed(evt);
            }
        });
        txtCityName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityNameKeyReleased(evt);
            }
        });

        lblCityName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCityName.setForeground(new java.awt.Color(10, 48, 58));
        lblCityName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCityName.setText("City Name:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText(" ");
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel2KeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText(" ");
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel3KeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText(" ");
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel4KeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText(" ");
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel5KeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText(" ");
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel6KeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText(" ");
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel7KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText(" ");

        btnBack.setBackground(new java.awt.Color(32, 37, 113));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle1.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle1.setFont(new java.awt.Font("Luminari", 1, 35)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(10, 48, 58));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Beth Israel Deaconess Medical Center");
        lblTitle1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblTitle2.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle2.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(10, 48, 58));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Address: 330 Brookline Ave, Boston, MA 02215  Phone: (617) 667-7000");

        lblTitle3.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle3.setFont(new java.awt.Font("Lucida Grande", 3, 30)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(10, 48, 58));
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Update Person Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblAddressLine2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAddressLine1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblCityName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAddressLine2)
                                    .addComponent(txtAddressLine1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFirstName)
                                            .addComponent(txtGender, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(btnPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle2)
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(53, 53, 53)
                .addComponent(btnPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-z]{0,30}$");
        Matcher match = pattern.matcher(txtFirstName.getText());
        boolean matchFound = match.matches();
        if(!matchFound){
            jLabel2.setText("Enter valid input data");
        }else{
            jLabel2.setText(null);
        }
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-z]{0,30}$");
        Matcher match = pattern.matcher(txtLastName.getText());
        boolean matchFound = match.matches();
        if(!matchFound){
            jLabel3.setText("Enter valid input data");
        }else{
            jLabel3.setText(null);
        }
    }//GEN-LAST:event_txtLastNameKeyReleased

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenderKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-z]{0,30}$");
        Matcher match = pattern.matcher(txtGender.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            jLabel4.setText("Enter valid input data");
        }else{
            jLabel4.setText(null);
        }
    }//GEN-LAST:event_txtGenderKeyReleased

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[1-9]{1,2}$");
        Matcher match = pattern.matcher(txtAge.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            jLabel5.setText("Enter valid input data");
        }else{
            jLabel5.setText(null);
        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine1ActionPerformed

    private void txtAddressLine1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressLine1KeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-z0-9 ]{0,30}$");
        Matcher match = pattern.matcher(txtAddressLine1.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            jLabel6.setText("Enter valid input data");
        }else{
            jLabel6.setText(null);
        }
    }//GEN-LAST:event_txtAddressLine1KeyReleased

    private void txtAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine2ActionPerformed

    private void txtAddressLine2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressLine2KeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-z ]{0,30}$");
        Matcher match = pattern.matcher(txtAddressLine2.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            jLabel7.setText("Enter valid input data");
        }else{
            jLabel7.setText(null);
        }
    }//GEN-LAST:event_txtAddressLine2KeyReleased

    private void btnPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonActionPerformed
        // TODO add your handling code here:
         
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String gender = txtGender.getText();
        
        int age;
        try{
            age = Integer.parseInt(txtAge.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: Enter Correct Age");
            return;
        }
        String address1 = txtAddressLine1.getText();
        String address2 = txtAddressLine2.getText();
        String cityName = txtCityName.getText();
        String id = person.getId();
        
        
        if(person.getFirstName().equals(firstName) && person.getLastName().equals(lastName) && person.getGender().equals(gender)
                && person.getAge() == age && person.getHouse().getAddress().equals(address1) && person.getHouse().getCommunity().getCommunityName().equals(address2)
                && person.getHouse().getCommunity().getCity().getCityName().equals(cityName)){
            JOptionPane.showMessageDialog(null, "No changes made to the person data");
            return;
        }
        
        personDirectory.getTemporaryPersonDirectory().remove(person);
        personDirectory.getPersonDirectory().remove(person);
        
        Person person = new Person();
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setGender(gender);
        person.setAge(age);
        person.setId(id);
            
        if(cityMap.containsKey(cityName)){
            City city = cityMap.get(cityName);
            Community community = communityMap.get(address2);
            if(city.getCommunitySet().contains(community)){
                House house = houseMap.get(address1);  
                if(community.getHouseSet().contains(house)){
                    house.addPerson(person);      
                    person.setHouse(house);
                }else{
                    House houseNew = new House(address1);
                    community.addHouse(houseNew);
                    houseNew.setCommunity(community);
                    houseNew.addPerson(person);
                    person.setHouse(houseNew);
                    houseMap.put(address1, houseNew);
                }
            }else{
                Community communityNew = new Community(address2);
                city.addCommunity(communityNew);
                House house = new House(address1);
                communityNew.setCity(city);
                communityNew.addHouse(house);
                house.setCommunity(communityNew);
                house.addPerson(person);
                person.setHouse(house);
                communityMap.put(address2, communityNew);
                houseMap.put(address1, house);
            }
        }else{
            City city = new City(cityName);
            Community community = new Community(address2);
            city.addCommunity(community);
            House house = new House(address1);
            community.setCity(city);
            community.addHouse(house);
            house.setCommunity(community);
            house.addPerson(person);
            person.setHouse(house);
            cityMap.put(cityName, city);
            communityMap.put(address2, community);
            houseMap.put(address1, house);
        }
        
        if(txtFirstName.getText().isEmpty() || txtGender.getText().isEmpty() || txtLastName.getText().isEmpty()
                || txtAge.getText().isEmpty() || txtAddressLine1.getText().isEmpty() || txtAddressLine2.getText().isEmpty() || txtCityName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Entered Empty Data. Please try again");
            return;
        }
        
        personDirectory.addPerson(person);
        personDirectory.getTemporaryPersonDirectory().add(person);
        
        
        
//        if(houseMap.containsKey(address1)){
//            House house = houseMap.get(address1);
//            if(!person.getHouse().getAddress().equals(address1)){
//                house.addPerson(person);
//                person.getHouse().getCommunity().getCity().getCommunitySet().remove(person.getHouse().getCommunity());
//                person.getHouse().getPersonList().remove(person);
//                person.getHouse().getCommunity().getHouseSet().remove(person.getHouse());
//            }
//            person.setHouse(house);
//        }else{
//            House house = new House(address1);
//            house.addPerson(person);
//            person.getHouse().getPersonList().remove(person);
//            person.setHouse(house);
//            houseMap.put(address1, house);
//        }
//        
//        if(communityMap.containsKey(address2)){
//            Community community = communityMap.get(address2);
//            if(person.getHouse().getCommunity()==null){
//                community.addHouse(person.getHouse());
//            }
//            person.getHouse().setCommunity(community);
//        }else{
//            System.out.println("New Community created");
//            Community community = new Community(address2);
//            System.out.println(community.getCommunityName() + " This is community address");
//            community.addHouse(person.getHouse());
//            person.getHouse().setCommunity(community);
//            System.out.println(person.getHouse().getCommunity().getCommunityName() + " This should not be null");
//            communityMap.put(address2, community);
//        }
//
//        if(cityMap.containsKey(cityName)){
//            City city = cityMap.get(cityName);
//            if(person.getHouse().getCommunity().getCity()==null){
//                city.addCommunity(person.getHouse().getCommunity());
//            }
//            person.getHouse().getCommunity().setCity(city);        
//        }else{
//            City city = new City(cityName);
//            city.addCommunity(person.getHouse().getCommunity());
//            person.getHouse().getCommunity().setCity(city);
//            cityMap.put(cityName, city);
//        }
        
        populateTable();
            
        JOptionPane.showMessageDialog(null, "Person Details Sucessfully Updated");
    }//GEN-LAST:event_btnPersonActionPerformed

    private void txtCityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityNameActionPerformed

    private void txtCityNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityNameKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-z ]{0,30}$");
        Matcher match = pattern.matcher(txtCityName.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            jLabel8.setText("Enter valid input data");
        }else{
            jLabel8.setText(null);
        }
    }//GEN-LAST:event_txtCityNameKeyReleased

    private void jLabel2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel2KeyReleased

    private void jLabel3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel3KeyReleased

    private void jLabel4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel4KeyReleased

    private void jLabel5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel5KeyReleased

    private void jLabel6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel6KeyReleased

    private void jLabel7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel7KeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPane.remove(this);
        CardLayout layout = (CardLayout) rightPane.getLayout();
        layout.previous(rightPane);

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPerson;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddressLine1;
    private javax.swing.JLabel lblAddressLine2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
