/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.BankAccountDetails;
import model.BasicDetails;
import model.CreateProfile;
import model.GeographicDetails;
import model.MedicalDetails;
import model.OnlineIdentityDetails;
import model.VehicleDetails;
import java.util.regex.*;

/**
 *
 * @author siddharthasavant
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    CreateProfile createProfile;
    BankAccountDetails bankAccountDetails;
    BasicDetails basicDetails;
    GeographicDetails geographicDetails;
    MedicalDetails medicalDetails;
    OnlineIdentityDetails onlineIdentityDetails;
    VehicleDetails vehicleDetails;
    
            
            
    public CreateJPanel(CreateProfile createProfile) {
        initComponents();
        this.createProfile = createProfile;
        
        bankAccountDetails = new BankAccountDetails();
        basicDetails = new BasicDetails();
        geographicDetails = new GeographicDetails();
        medicalDetails = new MedicalDetails();
        onlineIdentityDetails = new OnlineIdentityDetails();
        vehicleDetails = new VehicleDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BankAccountJPanel = new javax.swing.JPanel();
        lblBankAccountDetails = new javax.swing.JLabel();
        txtBankAccountType = new javax.swing.JTextField();
        lblBankAccountNumber = new javax.swing.JLabel();
        txtBankAccountNumber = new javax.swing.JTextField();
        lblRoutingNumber = new javax.swing.JLabel();
        txtRoutingNumber = new javax.swing.JTextField();
        lblBankAccountType = new javax.swing.JLabel();
        bankAccountDetailsError = new javax.swing.JLabel();
        VehicleJPanel = new javax.swing.JPanel();
        lblVehicleDetails = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        lblLicensePlate = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        lblVehicleIdentifier = new javax.swing.JLabel();
        txtVehicleIdentifier = new javax.swing.JTextField();
        vehicleDetailsError = new javax.swing.JLabel();
        MedicalJPanel = new javax.swing.JPanel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        lblBeneficiaryNumber = new javax.swing.JLabel();
        txtBeneficiaryNumber = new javax.swing.JTextField();
        lblMedicalDetails = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        medicalDetailsError = new javax.swing.JLabel();
        GeographicJPanel = new javax.swing.JPanel();
        lblGeographicDetails = new javax.swing.JLabel();
        lblPresentAddress = new javax.swing.JLabel();
        txtPresentAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtZipcode = new javax.swing.JTextField();
        lblPermanentAddress = new javax.swing.JLabel();
        txtPermanentAddress = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        geographicDetailsError = new javax.swing.JLabel();
        BasicJPanel = new javax.swing.JPanel();
        lblBasicDetails = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblMobileNumber = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblLinkedinProfile = new javax.swing.JLabel();
        txtLinkedinProfile = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblFaxNumber = new javax.swing.JLabel();
        txtFaxNumber = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        basicDetailsError = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        OnlineIdentityJPanel = new javax.swing.JPanel();
        lblOnlineIdentityDetails = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        lblPhotoAddress = new javax.swing.JLabel();
        lblBiometricAddress = new javax.swing.JLabel();
        lblDeviceIdentity = new javax.swing.JLabel();
        txtDeviceIdentity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        onlineIdentityDetailsError = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(208, 220, 235));
        setPreferredSize(new java.awt.Dimension(696, 448));

        BankAccountJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblBankAccountDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblBankAccountDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblBankAccountDetails.setText("Bank Account Details");

        txtBankAccountType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankAccountTypeKeyReleased(evt);
            }
        });

        lblBankAccountNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblBankAccountNumber.setText("Bank Account Number:");

        txtBankAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankAccountNumberKeyReleased(evt);
            }
        });

        lblRoutingNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblRoutingNumber.setText("Routing Number:");

        txtRoutingNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRoutingNumberKeyReleased(evt);
            }
        });

        lblBankAccountType.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblBankAccountType.setText("Bank Account Type:");

        bankAccountDetailsError.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        bankAccountDetailsError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout BankAccountJPanelLayout = new javax.swing.GroupLayout(BankAccountJPanel);
        BankAccountJPanel.setLayout(BankAccountJPanelLayout);
        BankAccountJPanelLayout.setHorizontalGroup(
            BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                        .addComponent(lblRoutingNumber)
                        .addGap(12, 12, 12)
                        .addComponent(txtRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                        .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                                .addComponent(lblBankAccountType)
                                .addGap(12, 12, 12)
                                .addComponent(txtBankAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(lblBankAccountNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                                .addComponent(lblBankAccountDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bankAccountDetailsError, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(91, Short.MAX_VALUE))))
        );
        BankAccountJPanelLayout.setVerticalGroup(
            BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BankAccountJPanelLayout.createSequentialGroup()
                .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBankAccountDetails)
                    .addComponent(bankAccountDetailsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBankAccountNumber)
                        .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBankAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBankAccountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoutingNumber)
                    .addComponent(txtRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        VehicleJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblVehicleDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblVehicleDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblVehicleDetails.setText("Vehicle Details");

        lblLicenseNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLicenseNumber.setText("License Number:");

        lblLicensePlate.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLicensePlate.setText("License Plate:");

        lblVehicleIdentifier.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblVehicleIdentifier.setText("Vehicle Identifier:");

        vehicleDetailsError.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        vehicleDetailsError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout VehicleJPanelLayout = new javax.swing.GroupLayout(VehicleJPanel);
        VehicleJPanel.setLayout(VehicleJPanelLayout);
        VehicleJPanelLayout.setHorizontalGroup(
            VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehicleJPanelLayout.createSequentialGroup()
                        .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VehicleJPanelLayout.createSequentialGroup()
                                .addComponent(lblVehicleIdentifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVehicleIdentifier))
                            .addGroup(VehicleJPanelLayout.createSequentialGroup()
                                .addComponent(lblLicenseNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(lblLicensePlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VehicleJPanelLayout.createSequentialGroup()
                        .addComponent(lblVehicleDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleDetailsError, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        VehicleJPanelLayout.setVerticalGroup(
            VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleJPanelLayout.createSequentialGroup()
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicleDetails)
                    .addComponent(vehicleDetailsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNumber)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicensePlate)
                    .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIdentifier)
                    .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MedicalJPanel.setBackground(new java.awt.Color(208, 220, 235));

        txtMedicalRecordNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicalRecordNumberKeyReleased(evt);
            }
        });

        lblBeneficiaryNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblBeneficiaryNumber.setText("Beneficiary Number:");

        txtBeneficiaryNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBeneficiaryNumberKeyReleased(evt);
            }
        });

        lblMedicalDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblMedicalDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblMedicalDetails.setText("Medical Details");

        lblMedicalRecordNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblMedicalRecordNumber.setText("Medical Record Number:");

        medicalDetailsError.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        medicalDetailsError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout MedicalJPanelLayout = new javax.swing.GroupLayout(MedicalJPanel);
        MedicalJPanel.setLayout(MedicalJPanelLayout);
        MedicalJPanelLayout.setHorizontalGroup(
            MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MedicalJPanelLayout.createSequentialGroup()
                        .addComponent(lblMedicalRecordNumber)
                        .addGap(16, 16, 16)
                        .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lblBeneficiaryNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MedicalJPanelLayout.createSequentialGroup()
                        .addComponent(lblMedicalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicalDetailsError, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        MedicalJPanelLayout.setVerticalGroup(
            MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalJPanelLayout.createSequentialGroup()
                .addGroup(MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicalDetails)
                    .addComponent(medicalDetailsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeneficiaryNumber)
                    .addComponent(txtBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicalRecordNumber)))
        );

        GeographicJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblGeographicDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblGeographicDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblGeographicDetails.setText("Geographic Details");

        lblPresentAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblPresentAddress.setText("Present Address:");

        txtZipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtZipcodeKeyReleased(evt);
            }
        });

        lblPermanentAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblPermanentAddress.setText("Permanent Address:");

        lblState.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblState.setText("State:");

        lblCity.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblCity.setText("City:");

        lblZipcode.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblZipcode.setText("Zipcode:");

        geographicDetailsError.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        geographicDetailsError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout GeographicJPanelLayout = new javax.swing.GroupLayout(GeographicJPanel);
        GeographicJPanel.setLayout(GeographicJPanelLayout);
        GeographicJPanelLayout.setHorizontalGroup(
            GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeographicJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GeographicJPanelLayout.createSequentialGroup()
                        .addComponent(lblPermanentAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPermanentAddress))
                    .addGroup(GeographicJPanelLayout.createSequentialGroup()
                        .addComponent(lblPresentAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPresentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeographicJPanelLayout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblState)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblZipcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZipcode))
                    .addGroup(GeographicJPanelLayout.createSequentialGroup()
                        .addComponent(lblGeographicDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(geographicDetailsError, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        GeographicJPanelLayout.setVerticalGroup(
            GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeographicJPanelLayout.createSequentialGroup()
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeographicDetails)
                    .addComponent(geographicDetailsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPresentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPresentAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPermanentAddress)
                    .addComponent(txtPermanentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipcode)
                    .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        BasicJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblBasicDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblBasicDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblBasicDetails.setText("Basic Details");

        lblFirstName.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblFirstName.setText("First Name:");

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });

        lblLastName.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLastName.setText("Last Name:");

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblGender.setText("Gender:");

        lblAge.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblAge.setText("Age:");

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        lblMobileNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblMobileNumber.setText("Mobile No.:");

        txtMobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobileNumberKeyReleased(evt);
            }
        });

        lblSSN.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblSSN.setText("Social Security No.:");

        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSSNKeyReleased(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblEmail.setText("Email:");

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        lblLinkedinProfile.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLinkedinProfile.setText("LinkedIn Profile:");

        lblDOB.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDOB.setText("Date of Birth:");

        lblFaxNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblFaxNumber.setText("Fax No.:");

        txtFaxNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxNumberKeyReleased(evt);
            }
        });

        jDateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooserKeyReleased(evt);
            }
        });

        basicDetailsError.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        basicDetailsError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout BasicJPanelLayout = new javax.swing.GroupLayout(BasicJPanel);
        BasicJPanel.setLayout(BasicJPanelLayout);
        BasicJPanelLayout.setHorizontalGroup(
            BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicJPanelLayout.createSequentialGroup()
                        .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BasicJPanelLayout.createSequentialGroup()
                                .addComponent(lblSSN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSSN))
                            .addGroup(BasicJPanelLayout.createSequentialGroup()
                                .addComponent(lblFirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblMobileNumber)
                        .addGap(5, 5, 5)
                        .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblDOB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblFaxNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblLinkedinProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLinkedinProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
            .addGroup(BasicJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBasicDetails)
                .addGap(4, 4, 4)
                .addComponent(basicDetailsError, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BasicJPanelLayout.setVerticalGroup(
            BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblBasicDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(basicDetailsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(lblLastName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName)))
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMobileNumber)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxNumber)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedinProfile)
                    .addComponent(txtLinkedinProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        BasicJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblGender, lblSSN});

        btnSubmit.setBackground(new java.awt.Color(208, 220, 235));
        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(51, 51, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        OnlineIdentityJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblOnlineIdentityDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblOnlineIdentityDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblOnlineIdentityDetails.setText("Online Identity Details");

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblAddress.setText("IP Address:");

        txtIPAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIPAddressKeyReleased(evt);
            }
        });

        lblPhotoAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblPhotoAddress.setText("Add Photo:");

        lblBiometricAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblBiometricAddress.setText("Add Biometric Data:");

        lblDeviceIdentity.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDeviceIdentity.setText("Device Identity:");

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Select Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Select Biometric Photo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        onlineIdentityDetailsError.setFont(new java.awt.Font("Lucida Grande", 2, 11)); // NOI18N
        onlineIdentityDetailsError.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout OnlineIdentityJPanelLayout = new javax.swing.GroupLayout(OnlineIdentityJPanel);
        OnlineIdentityJPanel.setLayout(OnlineIdentityJPanelLayout);
        OnlineIdentityJPanelLayout.setHorizontalGroup(
            OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                        .addComponent(lblOnlineIdentityDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onlineIdentityDetailsError, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                        .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OnlineIdentityJPanelLayout.createSequentialGroup()
                                .addComponent(lblBiometricAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OnlineIdentityJPanelLayout.createSequentialGroup()
                                .addComponent(lblAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                                .addComponent(lblPhotoAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                                .addComponent(lblDeviceIdentity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeviceIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(139, 157, Short.MAX_VALUE))
        );
        OnlineIdentityJPanelLayout.setVerticalGroup(
            OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOnlineIdentityDetails)
                    .addComponent(onlineIdentityDetailsError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeviceIdentity)
                    .addComponent(txtDeviceIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiometricAddress)
                    .addComponent(jButton2)
                    .addComponent(lblPhotoAddress)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator3.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator5.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator6.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator7.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator8.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4)
                            .addComponent(GeographicJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BankAccountJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MedicalJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BasicJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 804, Short.MAX_VALUE)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator3)
                            .addComponent(OnlineIdentityJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VehicleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BasicJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeographicJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BankAccountJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VehicleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OnlineIdentityJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        basicDetails.setFirstName(txtFirstName.getText());
        basicDetails.setLastName(txtLastName.getText());
        basicDetails.setDateOfBirth(jDateChooser.getDate());
        basicDetails.setGender(txtGender.getText());
        basicDetails.setAge(Integer.parseInt(txtAge.getText()));
        basicDetails.setMobileNumber(txtMobileNumber.getText());
        basicDetails.setFaxNumber(txtFaxNumber.getText());
        basicDetails.setLinkedinProfile(txtLinkedinProfile.getText());
        basicDetails.setEmail(txtEmail.getText());
        
        geographicDetails.setPresentAddress(txtPresentAddress.getText());
        geographicDetails.setPermanentAddress(txtPermanentAddress.getText());
        geographicDetails.setCity(txtCity.getText());
        geographicDetails.setState(txtState.getText());
        geographicDetails.setZipCode(Integer.parseInt(txtZipcode.getText()));
        
        bankAccountDetails.setTypeOfAccount(txtBankAccountType.getText());
        bankAccountDetails.setBankAccountNumber(txtBankAccountNumber.getText());
        bankAccountDetails.setRoutingNumber(txtRoutingNumber.getText());
    
        medicalDetails.setMedicalRecordNumber(txtMedicalRecordNumber.getText());
        medicalDetails.setBeneficiaryNumber(txtBeneficiaryNumber.getText());
        
        vehicleDetails.setLicenseNumber(txtLicenseNumber.getText());
        vehicleDetails.setLicensePlate(txtLicensePlate.getText());
        vehicleDetails.setVehicleIdentifier(txtVehicleIdentifier.getText());
        
        onlineIdentityDetails.setIpAddress(txtIPAddress.getText());
        onlineIdentityDetails.setDeviceIdentifier(txtDeviceIdentity.getText());
        
        createProfile.setBankAccountDetails(bankAccountDetails);
        createProfile.setBasicDetails(basicDetails);
        createProfile.setGeographicDetails(geographicDetails);
        createProfile.setMedicalDetails(medicalDetails);
        createProfile.setVehicleDetails(vehicleDetails);
        createProfile.setOnlineIdentityDetails(onlineIdentityDetails);
        
        
        JOptionPane.showMessageDialog(null, "Profile Created Successfully");

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser=new JFileChooser();
        int returnVal = jFileChooser.showSaveDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            onlineIdentityDetails.setPhotoAddress(jFileChooser.getSelectedFile().getAbsolutePath());
            JOptionPane.showMessageDialog(null, "Photo Image Uploaded Successfully!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser=new JFileChooser();
        int returnVal = jFileChooser.showSaveDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            onlineIdentityDetails.setBiometricAddress(jFileChooser.getSelectedFile().getAbsolutePath());
            JOptionPane.showMessageDialog(null, "Biometric Image Uploaded Successfully!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-z]{0,30}$");
        Matcher match = pattern.matcher(txtFirstName.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            basicDetailsError.setText("Enter valid input data");
        }else{
            basicDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[a-zA-z]{0,30}$");
        Matcher match = pattern.matcher(txtLastName.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            basicDetailsError.setText("Enter valid input data");
        }else{
            basicDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtLastNameKeyReleased

    private void jDateChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[1-9][0-9]?$|^100$");
        Matcher match = pattern.matcher(txtAge.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            basicDetailsError.setText("Enter valid input data");
        }else{
            basicDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtMobileNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNumberKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[0-9+()-]{10,18}$");
        Matcher match = pattern.matcher(txtMobileNumber.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            basicDetailsError.setText("Enter valid input data");
        }else{
            basicDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtMobileNumberKeyReleased

    private void txtFaxNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumberKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[0-9+()-]{10,18}$");
        Matcher match = pattern.matcher(txtFaxNumber.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            basicDetailsError.setText("Enter valid input data");
        }else{
            basicDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtFaxNumberKeyReleased

    private void txtSSNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$");
        Matcher match = pattern.matcher(txtSSN.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            basicDetailsError.setText("Enter valid input data");
        }else{
            basicDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtSSNKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("");
        Matcher match = pattern.matcher(txtEmail.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            basicDetailsError.setText("Enter valid input data");
        }else{
            basicDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtZipcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipcodeKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[0-9]{5}$");
        Matcher match = pattern.matcher(txtZipcode.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            geographicDetailsError.setText("Enter valid input data");
        }else{
            geographicDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtZipcodeKeyReleased

    private void txtBankAccountTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankAccountTypeKeyReleased
        // TODO add your handling code here:
        String bankType = txtBankAccountType.getText();
        if(!(bankType.equalsIgnoreCase("Savings")||bankType.equalsIgnoreCase("Saving")||bankType.equalsIgnoreCase("Checkings")||bankType.equalsIgnoreCase("Checking"))){
            bankAccountDetailsError.setText("Enter valid input data");
        }else{
            bankAccountDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtBankAccountTypeKeyReleased

    private void txtBankAccountNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankAccountNumberKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[0-9]{10,12}$");
        Matcher match = pattern.matcher(txtBankAccountNumber.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            bankAccountDetailsError.setText("Enter valid input data");
        }else{
            bankAccountDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtBankAccountNumberKeyReleased

    private void txtRoutingNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRoutingNumberKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[0-9]{9}$");
        Matcher match = pattern.matcher(txtRoutingNumber.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            bankAccountDetailsError.setText("Enter valid input data");
        }else{
            bankAccountDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtRoutingNumberKeyReleased

    private void txtMedicalRecordNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicalRecordNumberKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[0-9]{11}$");
        Matcher match = pattern.matcher(txtMedicalRecordNumber.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            medicalDetailsError.setText("Enter valid input data");
        }else{
            medicalDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtMedicalRecordNumberKeyReleased

    private void txtBeneficiaryNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeneficiaryNumberKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^[0-9]{9}$");
        Matcher match = pattern.matcher(txtBeneficiaryNumber.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            medicalDetailsError.setText("Enter valid input data");
        }else{
            medicalDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtBeneficiaryNumberKeyReleased

    private void txtIPAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPAddressKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\\.(?!$)|$)){4}$");
        Matcher match = pattern.matcher(txtIPAddress.getText());
        boolean matchFound = match.find();
        if(!matchFound){
            onlineIdentityDetailsError.setText("Enter valid input data");
        }else{
            onlineIdentityDetailsError.setText(null);
        }
    }//GEN-LAST:event_txtIPAddressKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BankAccountJPanel;
    private javax.swing.JPanel BasicJPanel;
    private javax.swing.JPanel GeographicJPanel;
    private javax.swing.JPanel MedicalJPanel;
    private javax.swing.JPanel OnlineIdentityJPanel;
    private javax.swing.JPanel VehicleJPanel;
    private javax.swing.JLabel bankAccountDetailsError;
    private javax.swing.JLabel basicDetailsError;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel geographicDetailsError;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBankAccountDetails;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblBankAccountType;
    private javax.swing.JLabel lblBasicDetails;
    private javax.swing.JLabel lblBeneficiaryNumber;
    private javax.swing.JLabel lblBiometricAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceIdentity;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGeographicDetails;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblLinkedinProfile;
    private javax.swing.JLabel lblMedicalDetails;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblOnlineIdentityDetails;
    private javax.swing.JLabel lblPermanentAddress;
    private javax.swing.JLabel lblPhotoAddress;
    private javax.swing.JLabel lblPresentAddress;
    private javax.swing.JLabel lblRoutingNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblVehicleDetails;
    private javax.swing.JLabel lblVehicleIdentifier;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JLabel medicalDetailsError;
    private javax.swing.JLabel onlineIdentityDetailsError;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtBankAccountType;
    private javax.swing.JTextField txtBeneficiaryNumber;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDeviceIdentity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtLinkedinProfile;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtPermanentAddress;
    private javax.swing.JTextField txtPresentAddress;
    private javax.swing.JTextField txtRoutingNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtVehicleIdentifier;
    private javax.swing.JTextField txtZipcode;
    private javax.swing.JLabel vehicleDetailsError;
    // End of variables declaration//GEN-END:variables
}
