/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import model.CreateProfile;


/**
 *
 * @author siddharthasavant
 */
public class ViewJPanel extends javax.swing.JPanel {

    CreateProfile createProfile;
    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(CreateProfile createProfile) {
        initComponents();
        this.createProfile = createProfile;
        displayProfile(createProfile);
    }
    
    private void displayProfile(CreateProfile createProfile){
        String firstName = createProfile.getBasicDetails().getFirstName();
        String lastName = createProfile.getBasicDetails().getLastName();
        Date dateOfBirth = createProfile.getBasicDetails().getDateOfBirth();
        String gender = createProfile.getBasicDetails().getGender();
        String mobileNumber = createProfile.getBasicDetails().getMobileNumber();
        String faxNumber = createProfile.getBasicDetails().getFaxNumber();
        String socialSecurityNumber = createProfile.getBasicDetails().getSocialSecurityNumber();
        String email = createProfile.getBasicDetails().getEmail();
        String linkedinProfile = createProfile.getBasicDetails().getLinkedinProfile();
        int age = createProfile.getBasicDetails().getAge();
        
        txtFirstName.setText(firstName);
        txtLastName.setText(lastName);
        txtDOB.setText(new SimpleDateFormat("MM-dd-yyyy").format(dateOfBirth));
        //txtDOB.setText(dateOfBirth);
        txtGender.setText(gender);
        txtMobileNumber.setText(mobileNumber);
        txtFaxNumber.setText(faxNumber);
        txtSSN.setText(socialSecurityNumber);
        txtEmail.setText(email);
        txtLinkedinProfile.setText(linkedinProfile);
        txtAge.setText(Integer.toString(age));
        
        txtPresentAddress.setText(createProfile.getGeographicDetails().getPresentAddress());
        txtPermanentAddress.setText(createProfile.getGeographicDetails().getPermanentAddress());
        txtCity.setText(createProfile.getGeographicDetails().getCity());
        txtState.setText(createProfile.getGeographicDetails().getState());
        txtZipcode.setText(Integer.toString(createProfile.getGeographicDetails().getZipCode()));

        txtBankAccountType.setText(createProfile.getBankAccountDetails().getTypeOfAccount());
        txtBankAccountNumber.setText(createProfile.getBankAccountDetails().getBankAccountNumber());
        txtRoutingNumber.setText(createProfile.getBankAccountDetails().getRoutingNumber());
        
        txtMedicalRecordNumber.setText(createProfile.getMedicalDetails().getMedicalRecordNumber());
        txtBeneficiaryNumber.setText(createProfile.getMedicalDetails().getBeneficiaryNumber());
        
        txtLicenseNumber.setText(createProfile.getVehicleDetails().getLicenseNumber());
        txtLicensePlate.setText(createProfile.getVehicleDetails().getLicensePlate());
        txtVehicleIdentifier.setText(createProfile.getVehicleDetails().getVehicleIdentifier());
        
        txtIPAddress.setText(createProfile.getOnlineIdentityDetails().getIpAddress());
        txtDeviceIdentity.setText(createProfile.getOnlineIdentityDetails().getDeviceIdentifier());
        
        String photoPath = createProfile.getOnlineIdentityDetails().getPhotoAddress();
        String biometricPath = createProfile.getOnlineIdentityDetails().getBiometricAddress();
        
        ImageIcon imageIcon = new ImageIcon(photoPath);
        Image image = imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        photoPicture.setIcon(new ImageIcon(image));
        
        imageIcon = new ImageIcon(biometricPath);
        Image image2 = imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        biometricPicture.setIcon(new ImageIcon(image2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BankAccountJPanel = new javax.swing.JPanel();
        lblBankAccountDetails = new javax.swing.JLabel();
        txtBankAccountType = new javax.swing.JTextField();
        lblBankAccountNumber = new javax.swing.JLabel();
        txtBankAccountNumber = new javax.swing.JTextField();
        lblRoutingNumber = new javax.swing.JLabel();
        txtRoutingNumber = new javax.swing.JTextField();
        lblBankAccountType = new javax.swing.JLabel();
        MedicalJPanel = new javax.swing.JPanel();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        lblBeneficiaryNumber = new javax.swing.JLabel();
        txtBeneficiaryNumber = new javax.swing.JTextField();
        lblMedicalDetails = new javax.swing.JLabel();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        VehicleJPanel = new javax.swing.JPanel();
        lblVehicleDetails = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JTextField();
        lblLicensePlate = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        lblVehicleIdentifier = new javax.swing.JLabel();
        txtVehicleIdentifier = new javax.swing.JTextField();
        GeographicJPanel = new javax.swing.JPanel();
        lblGeographicDetails = new javax.swing.JLabel();
        lblPresentAddress = new javax.swing.JLabel();
        txtPresentAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtZipcode = new javax.swing.JTextField();
        lblPermanentAddress = new javax.swing.JLabel();
        txtPermanentAddress = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        BasicJPanel = new javax.swing.JPanel();
        lblBasicDetails = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblMobileNumber = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblLinkedinProfile = new javax.swing.JLabel();
        txtLinkedinProfile = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblFaxNumber = new javax.swing.JLabel();
        txtFaxNumber = new javax.swing.JTextField();
        OnlineIdentityJPanel = new javax.swing.JPanel();
        lblOnlineIdentityDetails = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        lblPhotoAddress = new javax.swing.JLabel();
        lblBiometricAddress = new javax.swing.JLabel();
        lblDeviceIdentity = new javax.swing.JLabel();
        txtDeviceIdentity = new javax.swing.JTextField();
        photoPicture = new javax.swing.JLabel();
        biometricPicture = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(208, 220, 235));

        BankAccountJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblBankAccountDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblBankAccountDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblBankAccountDetails.setText("Bank Account Details");

        lblBankAccountNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblBankAccountNumber.setText("Bank Account Number:");

        lblRoutingNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblRoutingNumber.setText("Routing Number:");

        lblBankAccountType.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblBankAccountType.setText("Bank Account Type:");

        javax.swing.GroupLayout BankAccountJPanelLayout = new javax.swing.GroupLayout(BankAccountJPanel);
        BankAccountJPanel.setLayout(BankAccountJPanelLayout);
        BankAccountJPanelLayout.setHorizontalGroup(
            BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                        .addComponent(lblBankAccountType)
                        .addGap(12, 12, 12)
                        .addComponent(txtBankAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBankAccountNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                        .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BankAccountJPanelLayout.createSequentialGroup()
                                .addComponent(lblRoutingNumber)
                                .addGap(12, 12, 12)
                                .addComponent(txtRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBankAccountDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 452, Short.MAX_VALUE))))
        );
        BankAccountJPanelLayout.setVerticalGroup(
            BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BankAccountJPanelLayout.createSequentialGroup()
                .addComponent(lblBankAccountDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBankAccountNumber)
                        .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBankAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBankAccountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BankAccountJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoutingNumber)
                    .addComponent(txtRoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        MedicalJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblBeneficiaryNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblBeneficiaryNumber.setText("Beneficiary Number:");

        lblMedicalDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblMedicalDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblMedicalDetails.setText("Medical Details");

        lblMedicalRecordNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblMedicalRecordNumber.setText("Medical Record Number:");

        javax.swing.GroupLayout MedicalJPanelLayout = new javax.swing.GroupLayout(MedicalJPanel);
        MedicalJPanel.setLayout(MedicalJPanelLayout);
        MedicalJPanelLayout.setHorizontalGroup(
            MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MedicalJPanelLayout.createSequentialGroup()
                        .addComponent(lblMedicalRecordNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lblBeneficiaryNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMedicalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        MedicalJPanelLayout.setVerticalGroup(
            MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalJPanelLayout.createSequentialGroup()
                .addComponent(lblMedicalDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MedicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeneficiaryNumber)
                    .addComponent(txtBeneficiaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicalRecordNumber))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        VehicleJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblVehicleDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblVehicleDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblVehicleDetails.setText("Vehicle Details");

        lblLicenseNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLicenseNumber.setText("License Number:");

        lblLicensePlate.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLicensePlate.setText("License Plate:");

        lblVehicleIdentifier.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblVehicleIdentifier.setText("Vehicle Identifier:");

        javax.swing.GroupLayout VehicleJPanelLayout = new javax.swing.GroupLayout(VehicleJPanel);
        VehicleJPanel.setLayout(VehicleJPanelLayout);
        VehicleJPanelLayout.setHorizontalGroup(
            VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehicleDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VehicleJPanelLayout.createSequentialGroup()
                        .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VehicleJPanelLayout.createSequentialGroup()
                                .addComponent(lblVehicleIdentifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VehicleJPanelLayout.createSequentialGroup()
                                .addComponent(lblLicenseNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(lblLicensePlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        VehicleJPanelLayout.setVerticalGroup(
            VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleJPanelLayout.createSequentialGroup()
                .addComponent(lblVehicleDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNumber)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicensePlate)
                    .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIdentifier)
                    .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GeographicJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblGeographicDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblGeographicDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblGeographicDetails.setText("Geographic Details");

        lblPresentAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblPresentAddress.setText("Present Address:");

        lblPermanentAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblPermanentAddress.setText("Permanent Address:");

        lblState.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblState.setText("State:");

        lblCity.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblCity.setText("City:");

        lblZipcode.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblZipcode.setText("Zipcode:");

        javax.swing.GroupLayout GeographicJPanelLayout = new javax.swing.GroupLayout(GeographicJPanel);
        GeographicJPanel.setLayout(GeographicJPanelLayout);
        GeographicJPanelLayout.setHorizontalGroup(
            GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeographicJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GeographicJPanelLayout.createSequentialGroup()
                        .addComponent(lblPermanentAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPermanentAddress))
                    .addGroup(GeographicJPanelLayout.createSequentialGroup()
                        .addComponent(lblPresentAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPresentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeographicJPanelLayout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblState)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblZipcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZipcode))
                    .addComponent(lblGeographicDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        GeographicJPanelLayout.setVerticalGroup(
            GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeographicJPanelLayout.createSequentialGroup()
                .addComponent(lblGeographicDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPresentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPresentAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPermanentAddress)
                    .addComponent(txtPermanentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeographicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZipcode)
                    .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BasicJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblBasicDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblBasicDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblBasicDetails.setText("Basic Details");

        lblFirstName.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblFirstName.setText("First Name:");

        lblLastName.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLastName.setText("Last Name:");

        lblGender.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblGender.setText("Gender:");

        lblAge.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblAge.setText("Age:");

        lblMobileNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblMobileNumber.setText("Mobile No.:");

        lblSSN.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblSSN.setText("Social Security No.:");

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblEmail.setText("Email:");

        lblLinkedinProfile.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblLinkedinProfile.setText("LinkedIn Profile:");

        lblDOB.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDOB.setText("Date of Birth:");

        lblFaxNumber.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblFaxNumber.setText("Fax No.:");

        javax.swing.GroupLayout BasicJPanelLayout = new javax.swing.GroupLayout(BasicJPanel);
        BasicJPanel.setLayout(BasicJPanelLayout);
        BasicJPanelLayout.setHorizontalGroup(
            BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicJPanelLayout.createSequentialGroup()
                        .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BasicJPanelLayout.createSequentialGroup()
                                .addComponent(lblSSN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSSN))
                            .addGroup(BasicJPanelLayout.createSequentialGroup()
                                .addComponent(lblFirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblMobileNumber)
                        .addGap(5, 5, 5)
                        .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(BasicJPanelLayout.createSequentialGroup()
                            .addComponent(lblFaxNumber)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFaxNumber))
                        .addGroup(BasicJPanelLayout.createSequentialGroup()
                            .addComponent(lblDOB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BasicJPanelLayout.createSequentialGroup()
                        .addComponent(lblLinkedinProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLinkedinProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98))
            .addGroup(BasicJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBasicDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BasicJPanelLayout.setVerticalGroup(
            BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBasicDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMobileNumber)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxNumber)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedinProfile)
                    .addComponent(txtLinkedinProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OnlineIdentityJPanel.setBackground(new java.awt.Color(208, 220, 235));

        lblOnlineIdentityDetails.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lblOnlineIdentityDetails.setForeground(new java.awt.Color(0, 0, 255));
        lblOnlineIdentityDetails.setText("Online Identity Details");

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblAddress.setText("IP Address:");

        lblPhotoAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblPhotoAddress.setText("Photo:");

        lblBiometricAddress.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblBiometricAddress.setText("Biometric Photo:");

        lblDeviceIdentity.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblDeviceIdentity.setText("Device Identity:");

        javax.swing.GroupLayout OnlineIdentityJPanelLayout = new javax.swing.GroupLayout(OnlineIdentityJPanel);
        OnlineIdentityJPanel.setLayout(OnlineIdentityJPanelLayout);
        OnlineIdentityJPanelLayout.setHorizontalGroup(
            OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOnlineIdentityDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                        .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblBiometricAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(photoPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPhotoAddress))
                            .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lblDeviceIdentity)))
                        .addGap(18, 18, 18)
                        .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeviceIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biometricPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, Short.MAX_VALUE))
        );
        OnlineIdentityJPanelLayout.setVerticalGroup(
            OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                .addComponent(lblOnlineIdentityDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeviceIdentity)
                    .addComponent(txtDeviceIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBiometricAddress)
                            .addComponent(photoPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(OnlineIdentityJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(OnlineIdentityJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biometricPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhotoAddress))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jSeparator3.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator5.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator6.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator7.setForeground(new java.awt.Color(102, 102, 255));
        jSeparator7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BankAccountJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BasicJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 794, Short.MAX_VALUE)))
                    .addComponent(OnlineIdentityJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehicleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedicalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeographicJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
            .addComponent(jSeparator7)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BasicJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(GeographicJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BankAccountJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VehicleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OnlineIdentityJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BankAccountJPanel;
    private javax.swing.JPanel BasicJPanel;
    private javax.swing.JPanel GeographicJPanel;
    private javax.swing.JPanel MedicalJPanel;
    private javax.swing.JPanel OnlineIdentityJPanel;
    private javax.swing.JPanel VehicleJPanel;
    private javax.swing.JLabel biometricPicture;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBankAccountDetails;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblBankAccountType;
    private javax.swing.JLabel lblBasicDetails;
    private javax.swing.JLabel lblBeneficiaryNumber;
    private javax.swing.JLabel lblBiometricAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceIdentity;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGeographicDetails;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblLinkedinProfile;
    private javax.swing.JLabel lblMedicalDetails;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblOnlineIdentityDetails;
    private javax.swing.JLabel lblPermanentAddress;
    private javax.swing.JLabel lblPhotoAddress;
    private javax.swing.JLabel lblPresentAddress;
    private javax.swing.JLabel lblRoutingNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblVehicleDetails;
    private javax.swing.JLabel lblVehicleIdentifier;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JLabel photoPicture;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtBankAccountType;
    private javax.swing.JTextField txtBeneficiaryNumber;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDeviceIdentity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtLinkedinProfile;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtPermanentAddress;
    private javax.swing.JTextField txtPresentAddress;
    private javax.swing.JTextField txtRoutingNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtVehicleIdentifier;
    private javax.swing.JTextField txtZipcode;
    // End of variables declaration//GEN-END:variables
}
